redis: generate redis.conf only once

diff --git a/redis/replication/statefulset.yaml b/redis/replication/statefulset.yaml
--- a/redis/replication/statefulset.yaml
+++ b/redis/replication/statefulset.yaml
@@ -52,36 +52,38 @@ spec:
         - -c
         - |
           set -eo pipefail
-          HOST=$(hostname -s)
-          DOMAIN=$(hostname -d | cut -d. -f2-)
-          until getent hosts $HOST.$DOMAIN >/dev/null 2>&1; do
-              echo $HOST.$DOMAIN is not yet resolvable. waiting...
-              sleep 2
-          done
-          SERVICE_IP=$(getent hosts $HOST.$DOMAIN | awk '{ print $1 }')
-          mkdir -p /data/conf /data/db
-          cp /configtmp/redis.conf /data/conf/redis.conf
-          sed -i -e "s/\${SERVICE_IP}/$SERVICE_IP/g" \
-                 -e "s/\${USER_NAME}/$USER_NAME/g" \
-                 -e "s/\${PASSWORD}/$PASSWORD/g" /data/conf/redis.conf
-
-          if [[ $HOST =~ (.*)-([0-9]+)$ ]]; then
-              NAME=${BASH_REMATCH[1]}
-              ORD=${BASH_REMATCH[2]}
-          else
-              echo "Failed to parse hostname $HOST"
-              exit 1
-          fi
-          if [ "$ORD" != "0" ]; then
-              until getent hosts $NAME-0.$DOMAIN >/dev/null 2>&1; do
-                  echo $NAME-0.$DOMAIN is not yet resolvable. waiting...
+          if [ ! -f /data/conf/redis.conf ]; then
+              HOST=$(hostname -s)
+              DOMAIN=$(hostname -d | cut -d. -f2-)
+              until getent hosts $HOST.$DOMAIN >/dev/null 2>&1; do
+                  echo $HOST.$DOMAIN is not yet resolvable. waiting...
                   sleep 2
               done
-              MASTER_IP=$(getent hosts $NAME-0.$DOMAIN | awk '{ print $1 }')
-              echo >> /data/conf/redis.conf
-              echo "replicaof ${MASTER_IP} 6379" >> /data/conf/redis.conf
-          fi
+              SERVICE_IP=$(getent hosts $HOST.$DOMAIN | awk '{ print $1 }')
+              mkdir -p /data/conf /data/db
+              sed -e "s/\${SERVICE_IP}/$SERVICE_IP/g" \
+                  -e "s/\${USER_NAME}/$USER_NAME/g" \
+                  -e "s/\${PASSWORD}/$PASSWORD/g" \
+                  /configtmp/redis.conf > /tmp/redis.conf
 
+              if [[ $HOST =~ (.*)-([0-9]+)$ ]]; then
+                  NAME=${BASH_REMATCH[1]}
+                  ORD=${BASH_REMATCH[2]}
+              else
+                  echo "Failed to parse hostname $HOST"
+                  exit 1
+              fi
+              if [ "$ORD" != "0" ]; then
+                  until getent hosts $NAME-0.$DOMAIN >/dev/null 2>&1; do
+                      echo $NAME-0.$DOMAIN is not yet resolvable. waiting...
+                      sleep 2
+                  done
+                  MASTER_IP=$(getent hosts $NAME-0.$DOMAIN | awk '{ print $1 }')
+                  echo >> /tmp/redis.conf
+                  echo "replicaof ${MASTER_IP} 6379" >> /tmp/redis.conf
+              fi
+              mv /tmp/redis.conf /data/conf/redis.conf
+          fi
           exec "$@"
         - --
         args:
