shebangs are ignored by `sh -c`

diff --git a/elasticsearch/kustomize/statefulset.yaml b/elasticsearch/kustomize/statefulset.yaml
--- a/elasticsearch/kustomize/statefulset.yaml
+++ b/elasticsearch/kustomize/statefulset.yaml
@@ -73,8 +73,8 @@ spec:
         - name: ES_JAVA_OPTS
           value: -Xmx1g -Xms1g
         volumeMounts:
-          - name: datadir
-            mountPath: /usr/share/elasticsearch/data
+        - name: datadir
+          mountPath: /usr/share/elasticsearch/data
         resources:
           limits:
             cpu: 1000m
@@ -82,47 +82,46 @@ spec:
         readinessProbe:
           exec:
             command:
-              - sh
-              - -c
-              - |
-                #!/usr/bin/env bash
-                set -e
+            - bash
+            - -c
+            - |
+              set -e
 
-                # If the node is starting up wait for the cluster to be ready (request params: 'wait_for_status=green&timeout=1s' )
-                # Once it has started only check that the node itself is responding
-                START_FILE=/tmp/.es_start_file
+              # If the node is starting up wait for the cluster to be ready (request params: 'wait_for_status=green&timeout=1s' )
+              # Once it has started only check that the node itself is responding
+              START_FILE=/tmp/.es_start_file
 
-                if [ -n "${ELASTIC_USERNAME}" ] && [ -n "${ELASTIC_PASSWORD}" ]; then
-                  BASIC_AUTH="-u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}"
-                else
-                  BASIC_AUTH=''
+              if [ -n "${ELASTIC_USERNAME}" ] && [ -n "${ELASTIC_PASSWORD}" ]; then
+                BASIC_AUTH="-u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}"
+              else
+                BASIC_AUTH=''
+              fi
+
+              if [ -f "${START_FILE}" ]; then
+                echo 'Elasticsearch is already running, lets check the node is healthy'
+                HTTP_CODE=$(curl -XGET -s -k ${BASIC_AUTH} -o /dev/null -w '%{http_code}' http://127.0.0.1:9200/)
+                RC=$?
+                if [[ ${RC} -ne 0 ]]; then
+                  echo "curl -XGET -s -k \${BASIC_AUTH} -o /dev/null -w '%{http_code}' http://127.0.0.1:9200/ failed with RC ${RC}"
+                  exit ${RC}
                 fi
-
-                if [ -f "${START_FILE}" ]; then
-                  echo 'Elasticsearch is already running, lets check the node is healthy'
-                  HTTP_CODE=$(curl -XGET -s -k ${BASIC_AUTH} -o /dev/null -w '%{http_code}' http://127.0.0.1:9200/)
-                  RC=$?
-                  if [[ ${RC} -ne 0 ]]; then
-                    echo "curl -XGET -s -k \${BASIC_AUTH} -o /dev/null -w '%{http_code}' http://127.0.0.1:9200/ failed with RC ${RC}"
-                    exit ${RC}
-                  fi
-                  # ready if HTTP code 200, 503 is tolerable if ES version is 6.x
-                  if [[ ${HTTP_CODE} == "200" ]]; then
-                    exit 0
-                  else
-                    echo "curl -XGET -s -k \${BASIC_AUTH} -o /dev/null -w '%{http_code}' http://127.0.0.1:9200/ failed with HTTP code ${HTTP_CODE}"
-                    exit 1
-                  fi
+                # ready if HTTP code 200, 503 is tolerable if ES version is 6.x
+                if [[ ${HTTP_CODE} == "200" ]]; then
+                  exit 0
                 else
-                  echo 'Waiting for elasticsearch cluster to become ready (request params: "wait_for_status=green&timeout=1s" )'
-                  if curl -XGET -s -k --fail ${BASIC_AUTH} http://127.0.0.1:9200/_cluster/health?wait_for_status=green&timeout=1s ; then
-                    touch ${START_FILE}
-                    exit 0
-                  else
-                    echo 'Cluster is not yet ready (request params: "wait_for_status=green&timeout=1s" )'
-                    exit 1
-                  fi
+                  echo "curl -XGET -s -k \${BASIC_AUTH} -o /dev/null -w '%{http_code}' http://127.0.0.1:9200/ failed with HTTP code ${HTTP_CODE}"
+                  exit 1
                 fi
+              else
+                echo 'Waiting for elasticsearch cluster to become ready (request params: "wait_for_status=green&timeout=1s" )'
+                if curl -XGET -s -k --fail ${BASIC_AUTH} http://127.0.0.1:9200/_cluster/health?wait_for_status=green&timeout=1s ; then
+                  touch ${START_FILE}
+                  exit 0
+                else
+                  echo 'Cluster is not yet ready (request params: "wait_for_status=green&timeout=1s" )'
+                  exit 1
+                fi
+              fi
           initialDelaySeconds: 10
           successThreshold: 3
           timeoutSeconds: 5
